services:
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    networks:
      - nats-network
    volumes:
      - nats-data:/data
    command: ["-js"]

  subscriber:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - NATS_URL=nats://nats:4222
      - SUBJECT=example.subject
    networks:
      - nats-network
    depends_on:
      - nats

networks:
  nats-network:

volumes:
  nats-data: